---
- name: Install Node.js and npm, Deploy Node.js App
  hosts: web1
  become: yes  # Ensure you have privilege escalation, e.g., sudo

  tasks:
    - name: Update APT repositories and cache
      yum:
        update_cache: yes

    - name: Install the EPEL repository
      yum:
        name: epel-release
        state: present
    - name: Install Node.js and npm
      yum:
        name:
          - nodejs
          - npm
        state: present


- name: create new linux user for node app
  hosts: web1
  tasks: 
    - name: create linux user
      user:
        name: walid
        comment: walid admin
        group: admin 


- name: Deploy nodejs app
  hosts: web1
  become: True
  become_user: walid
  tasks:
    - name: Unpack the Node.js tar file
      unarchive:
        src: /home/thor/simple-nodejs/nodejs-app-1.0.0.tgz
        dest: /home/walid
       
    - name: install dependencies 
      npm:
        path: /home/walid/package
    - name: start the application
      command: 
        chdir: /root/package/app
        cmd: node server
      async: 1000
      poll: 0  

    - name: ensure app is running
      shell: ps aux | grep node
      register: app_status

    - debug: msg={{app_status}}

      
  